name: Generate the Doxygen documentation and publish it to the Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: langroodi/doxygenize@v1.3
      with:
        htmloutput:    './doc/html/'
        ghpagesbranch: 'gh-pages'
        ghpagesdir:    './docs/'
