name: Generate the Doxygen documentation and publish it to the GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Doxygen and publish to GitHub
        uses: langroodi/doxygenize@v1.4
        with:
          htmloutput:    './doc/html/'
          ghpagesbranch: 'gh-pages'
          ghpagesdir:    './docs/'
